name: Build and deploy Node.js app to Vercel - taskadventure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        run: |
          npm install --workspaces=false
          npm run -w backend build --if-present
          npm run -w backend test --if-present
        working-directory: packages/backend

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: packages/backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: packages/backend/release.zip

      - name: List files in backend folder
        run: ls -la
        working-directory: packages/backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          production: true
